"""team.1

Revision ID: 09c7c063ca1c
Revises: e51ee8bb912f
Create Date: 2025-11-05 16:31:30.067378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c7c063ca1c'
down_revision = 'e51ee8bb912f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=False))
        batch_op.drop_column('base')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('address')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
