"""season

Revision ID: 41abb843ce01
Revises: 7d5fd3e9866c
Create Date: 2025-11-18 10:18:40.467731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41abb843ce01'
down_revision = '7d5fd3e9866c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('season')
    # ### end Alembic commands ###
