"""team.3

Revision ID: 577703848676
Revises: e534c8fb97f8
Create Date: 2025-11-06 09:41:16.207268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577703848676'
down_revision = 'e534c8fb97f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('total_points',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('total_points',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
