"""driver

Revision ID: 90386d925f24
Revises: 577703848676
Create Date: 2025-11-06 15:03:32.675997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90386d925f24'
down_revision = '577703848676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_ref', sa.String(length=3), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('is_actual_champion', sa.Boolean(), nullable=True),
    sa.Column('is_using_number_one', sa.Boolean(), nullable=True),
    sa.Column('car_number', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=True),
    sa.Column('total_wins', sa.Integer(), nullable=True),
    sa.Column('total_podiums', sa.Integer(), nullable=True),
    sa.Column('number_championship_wins', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_ref')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver')
    # ### end Alembic commands ###
