"""circuit

Revision ID: 9bd5374a3313
Revises: 62348372494e
Create Date: 2025-10-30 16:58:06.771311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd5374a3313'
down_revision = '62348372494e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('first_grand_prix_year', sa.Integer(), nullable=False),
    sa.Column('length_km', sa.Float(), nullable=False),
    sa.Column('number_of_laps', sa.Integer(), nullable=False),
    sa.Column('fastest_lap_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('circuit')
    # ### end Alembic commands ###
