"""team

Revision ID: e51ee8bb912f
Revises: f860bd74e7dc
Create Date: 2025-11-05 16:24:12.767685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e51ee8bb912f'
down_revision = 'f860bd74e7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base', sa.String(length=100), nullable=False),
    sa.Column('team_principal', sa.String(length=100), nullable=False),
    sa.Column('founded_year', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('total_wins', sa.Integer(), nullable=True),
    sa.Column('championships_won', sa.Integer(), nullable=True),
    sa.Column('is_actual_champion', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    # ### end Alembic commands ###
