"""driver.2

Revision ID: ff0df7d23607
Revises: 90386d925f24
Create Date: 2025-11-06 15:18:02.235319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0df7d23607'
down_revision = '90386d925f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('number_championship_won', sa.Integer(), nullable=True))
        batch_op.drop_column('country')
        batch_op.drop_column('number_championship_wins')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_championship_wins', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('number_championship_won')
        batch_op.drop_column('nationality')

    # ### end Alembic commands ###
